### model
model_name_or_path: models/sft-mmlu-sample-3

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_dropout: 0.1
use_dora: true
lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: combine_data
template: llama3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/t3ai/lora/sft-mmlu-sample-3-combined
logging_steps: 5
save_steps: 150
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
ddp_timeout: 180000000
report_to: wandb
run_name: mmlu_sample_3_combined_data # optional
train_on_prompt: false

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
